input:
  connector: "postgres"
  dsn: "postgres://from-to-user:from-to-passw@localhost:5432/from-to-db?sslmode=disable"
  pollSeconds: 10
  tables:
    - from:
        name: "sales"
        keyColumn: "id"
      to:
        topic: "public_sales"
        partitions: 3
        replicationFactor: 1
      mapper:
        type: "lua"
        filePath: "./example/mappers.lua"
        function: "map_sales_event"

# The input configuration
output:
  connector: "kafka"
  bootstrapServers: "localhost:9094"
