input:
  type: "postgres"
  dsn: "postgres://from-to-user:from-to-passw@localhost:5432/from-to-db?sslmode=disable"
  pollSeconds: 10
  tables:
    - from:
        name: "sales"
        keyColumn: "id"
      to:
        topic: "public_sales"
        partitions: 3
        replicationFactor: 1
      mapper:
        type: "lua"
        filePath: "./mappers.lua"
        function: "map_sales_event"

output:
  type: "kafka"
  bootstrapServers: "localhost:9094"
